template: |
  ## What's Changed

  {{CHANGELOG}}

categories:
  - title: "ğŸš€ Features"
    labels:
      - feature
  - title: "ğŸ› Bug Fixes"
    labels:
      - bug
  - title: "ğŸ§° Maintenance"
    labels:
      - chore
      - ci
  - title: "ğŸ“ Documentation"
    labels:
      - documentation
      - docs
  - title: "ğŸ’¡ Refactoring"
    labels:
      - refactor

sort: DESC
max_pull_requests: 100
exclude_merge_branches: true
transform_issues: true
